// AUTO-GENERATED by scripts/golden/generate.ts — pure prelude of convex/moderation.ts. Do not edit.

// ─── Types ───────────────────────────────────────────────────────

interface RuleMatch {
  ruleName: string;
  ruleCategory: string;
  tier: string;
  action: string;
  message?: string;
  details?: string;
}

interface ListingData {
  _id: string;
  jeId: string;
  title: string;
  price?: number;
  priceUsd?: number;
  priceOnRequest?: boolean;
  category?: string;
  realEstateType?: string;
  country?: string;
  city?: string;
  imageCount?: number;
  avgImageWidth?: number;
  avgImageHeight?: number;
  lqi?: number;
  descriptionLength?: number;
  description?: string;
  office?: string;
  officeGroupName?: string;
  officeId?: string | number;
  officeSubscription?: string;
  accountType?: string;
  officeGroupId?: string;
  feedSource?: string;
  livingArea?: number;
  landArea?: number;
  bedrooms?: number;
  bathrooms?: number;
  pricePerSqm?: number;
  rental?: boolean;
  outdated?: boolean;
  chatGptConclusion?: string;
  chatGptPropertyCondition?: number;
  chatGptWatermarkShare?: number;
  chatGptWatermarkText?: string;
  chatGptImageQuality?: string;
  chatGptImageType?: string;
  imageUrls?: string[];
  listingUrl?: string;
  [key: string]: unknown;
}

interface RuleConfig {
  field?: string;
  operator?: string;
  value?: unknown;
  conditions?: Array<{ field: string; operator: string; value: unknown }>;
  patterns?: string[];
  fields?: string[];
  textLists?: Record<string, string[]>;
  officeIds?: string[];
  officeNames?: string[];
  [key: string]: unknown;
}

interface Rule {
  _id: string;
  name: string;
  displayName: string;
  category: string;
  tier: string;
  enabled: boolean;
  action: string;
  priority: number;
  config: RuleConfig;
  sellerMessage?: string;
}

// ─── Country Name ↔ Code Normalization ──────────────────────────
// Rules use ISO codes (ES, IT, PT) but listing data often has full names (Spain, Italy, Portugal).
// This map handles bidirectional normalization so country filters always match.
// Regions that JE sometimes uses instead of country names in humanized_location
const REGION_TO_COUNTRY_CODE: Record<string, string> = {
  "algarve": "PT", "lisbon": "PT", "madeira": "PT", "azores": "PT", "porto": "PT",
  "balearic islands": "ES", "andalusia": "ES", "catalonia": "ES", "canary islands": "ES",
  "valencia": "ES", "galicia": "ES", "basque country": "ES", "castile and león": "ES",
  "tuscany": "IT", "sardinia": "IT", "sicily": "IT", "lombardy": "IT", "lazio": "IT",
  "puglia": "IT", "apulia": "IT", "liguria": "IT", "umbria": "IT", "veneto": "IT",
  "campania": "IT", "emilia-romagna": "IT", "piedmont": "IT", "calabria": "IT",
  "provence-alpes-côte d'azur": "FR", "île-de-france": "FR", "occitanie": "FR",
  "nouvelle-aquitaine": "FR", "brittany": "FR", "normandy": "FR", "corsica": "FR",
  "crete": "GR", "peloponnese": "GR", "attica": "GR", "thessaly": "GR",
  "macedonia and thrace": "GR", "cyclades": "GR", "dodecanese": "GR", "ionian islands": "GR",
  "dubai": "AE", "abu dhabi": "AE", "sharjah": "AE",
  "bavaria": "DE", "scotland": "GB", "england": "GB", "wales": "GB",
  "queensland": "AU", "new south wales": "AU", "victoria": "AU",
  "florida": "US", "california": "US", "new york": "US", "texas": "US",
};

const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  // Full name → ISO code (lowercase keys for case-insensitive matching)
  "spain": "ES", "italy": "IT", "portugal": "PT", "france": "FR", "greece": "GR",
  "united states": "US", "usa": "US", "united kingdom": "GB", "uk": "GB",
  "germany": "DE", "austria": "AT", "switzerland": "CH", "netherlands": "NL",
  "belgium": "BE", "sweden": "SE", "norway": "NO", "denmark": "DK", "finland": "FI",
  "ireland": "IE", "croatia": "HR", "turkey": "TR", "cyprus": "CY", "malta": "MT",
  "monaco": "MC", "luxembourg": "LU", "andorra": "AD", "montenegro": "ME",
  "united arab emirates": "AE", "uae": "AE", "saudi arabia": "SA", "qatar": "QA",
  "bahrain": "BH", "oman": "OM", "kuwait": "KW", "thailand": "TH", "indonesia": "ID",
  "malaysia": "MY", "singapore": "SG", "philippines": "PH", "japan": "JP",
  "australia": "AU", "new zealand": "NZ", "canada": "CA", "mexico": "MX",
  "brazil": "BR", "argentina": "AR", "colombia": "CO", "chile": "CL",
  "south africa": "ZA", "morocco": "MA", "egypt": "EG", "kenya": "KE",
  "russia": "RU", "china": "CN", "india": "IN", "israel": "IL",
  "czech republic": "CZ", "czechia": "CZ", "poland": "PL", "hungary": "HU",
  "romania": "RO", "bulgaria": "BG", "slovakia": "SK", "slovenia": "SI",
  "estonia": "EE", "latvia": "LV", "lithuania": "LT",
  "st. martin": "MF", "saint martin": "MF", "sint maarten": "SX",
  "barbados": "BB", "bahamas": "BS", "jamaica": "JM", "costa rica": "CR",
  "panama": "PA", "dominican republic": "DO", "puerto rico": "PR",
  "cayman islands": "KY", "turks and caicos": "TC",
};

const COUNTRY_CODE_TO_NAME: Record<string, string> = {};
// Build reverse map (code → canonical name)
for (const [name, code] of Object.entries(COUNTRY_NAME_TO_CODE)) {
  if (!COUNTRY_CODE_TO_NAME[code]) {
    COUNTRY_CODE_TO_NAME[code] = name;
  }
}

/**
 * Check if a listing's country matches a countryFilter array.
 * Handles both ISO codes (ES, PT) and full names (Spain, Portugal).
 */
// "UK" is a common alias for the ISO code "GB" — normalize so filters using
// either spelling match listings using the other.
function normCountryCode(code: string): string {
  const uc = code.toUpperCase();
  return uc === "UK" ? "GB" : uc;
}

// Best-effort country → ISO code normalization for other modules
// (e.g. aiParamScan's high-cost-country thresholds).
function toCountryCode(country: string): string {
  const trimmed = (country || "").trim();
  if (!trimmed) return "";
  if (trimmed.length <= 3) return normCountryCode(trimmed);
  const lower = trimmed.toLowerCase();
  return COUNTRY_NAME_TO_CODE[lower] || REGION_TO_COUNTRY_CODE[lower] || trimmed.toUpperCase();
}

function countryMatches(listingCountry: string | undefined, filterValues: string[]): boolean {
  if (!listingCountry) return false;
  const lc = listingCountry.trim();
  const lcLower = lc.toLowerCase();

  // Direct match (exact or case-insensitive)
  if (filterValues.some(f => f.toLowerCase() === lcLower || f === lc)) return true;

  // Listing has full name → normalize to code and check
  const code = COUNTRY_NAME_TO_CODE[lcLower];
  if (code && filterValues.some(f => normCountryCode(f) === code)) return true;

  // Listing has code → check against full names in filter
  const ucLc = lc.toUpperCase();
  if (ucLc.length <= 3) {
    const canonicalName = COUNTRY_CODE_TO_NAME[normCountryCode(ucLc)];
    if (canonicalName && filterValues.some(f => f.toLowerCase() === canonicalName)) return true;
    if (filterValues.some(f => normCountryCode(f) === normCountryCode(ucLc))) return true;
  }

  // Region fallback: "Algarve" → PT, "Balearic Islands" → ES, etc.
  const regionCode = REGION_TO_COUNTRY_CODE[lcLower];
  if (regionCode && filterValues.some(f => normCountryCode(f) === regionCode)) return true;

  return false;
}

// ─── Core Moderation Engine ──────────────────────────────────────

function evaluateSimpleRule(listing: ListingData, config: RuleConfig): { matched: boolean; details: string } {
  // ─── Pre-flight filters: check if rule applies to this listing ───
  const filterChecks: string[] = [];

  // Country filter (handles both ISO codes and full names)
  if (config.countryFilter && Array.isArray(config.countryFilter)) {
    if (!countryMatches(listing.country, config.countryFilter)) {
      return { matched: false, details: `country ${listing.country} not in ${config.countryFilter}` };
    }
    filterChecks.push(`country=${listing.country} ✓`);
  }
  if (config.excludeCountries && Array.isArray(config.excludeCountries)) {
    if (listing.country && countryMatches(listing.country, config.excludeCountries)) {
      return { matched: false, details: `country ${listing.country} excluded` };
    }
  }

  // Category filter (real_estate, cars, etc.)
  if (config.categoryFilter && Array.isArray(config.categoryFilter)) {
    const rawCat = (listing.category || "").toLowerCase();
    // Normalize: "RealEstate" → "real_estate", "Car" → "cars", "car" → "cars"
    const cat = rawCat
      .replace("listing::", "")
      .replace("realestate", "real_estate")
      .replace(/^car$/i, "cars");
    // Empty category must not pass: ""'s substring check matches any filter.
    if (!cat) {
      return { matched: false, details: `category unknown, filter ${config.categoryFilter}` };
    }
    if (!config.categoryFilter.some((f: string) => {
      const normFilter = f.toLowerCase();
      return cat.includes(normFilter) || normFilter.includes(cat);
    })) {
      return { matched: false, details: `category ${listing.category} not in ${config.categoryFilter}` };
    }
  }

  // Account type filter (uses officeSubscription field)
  if (config.accountTypeFilter && Array.isArray(config.accountTypeFilter)) {
    const acct = (listing.officeSubscription || listing.accountType || "").toLowerCase();
    if (!acct || !config.accountTypeFilter.some((f: string) => acct.includes(f.toLowerCase()))) {
      return { matched: false, details: `accountType ${acct || "unknown"} not in ${config.accountTypeFilter}` };
    }
    filterChecks.push(`accountType=${acct} ✓`);
  }
  if (config.excludeAccountTypes && Array.isArray(config.excludeAccountTypes)) {
    const acct = (listing.officeSubscription || listing.accountType || "").toLowerCase();
    if (acct && config.excludeAccountTypes.some((f: string) => acct.includes(f.toLowerCase()))) {
      return { matched: false, details: `accountType ${acct} excluded` };
    }
  }

  // Real estate type filter
  if (config.typeFilter && Array.isArray(config.typeFilter)) {
    const reType = (listing.realEstateType || "").toLowerCase();
    if (!reType || !config.typeFilter.some((f: string) => reType.toLowerCase() === f.toLowerCase())) {
      return { matched: false, details: `type ${listing.realEstateType} not in ${config.typeFilter}` };
    }
  }
  if (config.excludeTypes && Array.isArray(config.excludeTypes)) {
    const reType = (listing.realEstateType || "").toLowerCase();
    if (reType && config.excludeTypes.some((f: string) => { const nf = f.toLowerCase().replace(/ /g, "_"); return reType === nf || reType === f.toLowerCase() || reType.replace(/_/g, " ") === f.toLowerCase(); })) {
      return { matched: false, details: `type ${listing.realEstateType} excluded` };
    }
  }

  // Office filter (uses office field)
  if (config.officeFilter && Array.isArray(config.officeFilter)) {
    const officeId = listing.office ? Number(listing.office) : (listing.officeId ? Number(listing.officeId) : null);
    if (!officeId || !config.officeFilter.includes(officeId)) {
      return { matched: false, details: `office ${officeId} not in ${config.officeFilter}` };
    }
    filterChecks.push(`office=${officeId} ✓`);
  }
  if (config.excludeOffices && Array.isArray(config.excludeOffices)) {
    const officeId = listing.office ? Number(listing.office) : (listing.officeId ? Number(listing.officeId) : null);
    if (officeId && config.excludeOffices.includes(officeId)) {
      return { matched: false, details: `office ${officeId} excluded` };
    }
  }

  // Group filter (uses officeGroupName field)
  if (config.groupFilter && Array.isArray(config.groupFilter)) {
    const groupId = listing.officeGroupName || listing.officeGroupId || "";
    if (!groupId || !config.groupFilter.some((f: string) => String(groupId) === f)) {
      return { matched: false, details: `group ${groupId} not in ${config.groupFilter}` };
    }
  }

  // Outdated filter
  if (config.outdated === true) {
    if (!listing.outdated) {
      return { matched: false, details: "listing not outdated" };
    }
  }

  // Rental filter
  if (config.rentalOnly === true) {
    if (!listing.rental) {
      return { matched: false, details: "not a rental" };
    }
  }
  if (config.nonRentalOnly === true) {
    if (listing.rental === true) {
      return { matched: false, details: "is a rental (nonRentalOnly)" };
    }
  }

  // Max/min price shorthand
  if (config.maxPrice !== undefined && config.maxPrice !== null) {
    const price = listing.priceUsd || listing.price || 0;
    if (price > Number(config.maxPrice)) {
      return { matched: false, details: `price ${price} > maxPrice ${config.maxPrice}` };
    }
  }
  if (config.minPrice !== undefined && config.minPrice !== null) {
    const price = listing.priceUsd || listing.price || 0;
    if (price < Number(config.minPrice)) {
      return { matched: false, details: `price ${price} < minPrice ${config.minPrice}` };
    }
  }

  // Title exclude keywords
  if (config.excludeTitleKeywords && Array.isArray(config.excludeTitleKeywords)) {
    const title = (listing.title || "").toLowerCase();
    if (config.excludeTitleKeywords.some((kw: string) => title.includes(kw.toLowerCase()))) {
      return { matched: false, details: "title contains excluded keyword" };
    }
  }

  // Feed source filter
  if (config.feedSourceFilter && Array.isArray(config.feedSourceFilter)) {
    const src = (listing.feedSource || "").toLowerCase();
    if (!src || !config.feedSourceFilter.some((f: string) => src.includes(f.toLowerCase()))) {
      return { matched: false, details: `feedSource ${listing.feedSource || "unknown"} not in ${config.feedSourceFilter}` };
    }
    filterChecks.push(`feedSource=${src} ✓`);
  }

  // ─── Evaluate conditions ───
  let conditionsMet = true;
  const condDetails: string[] = [...filterChecks];

  // Conditions: AND by default, OR when requireAll === false
  if (config.conditions) {
    const results = config.conditions.map((c: { field: string; operator: string; value: unknown }) => {
      const val = listing[c.field as keyof ListingData];
      return evaluateCondition(val, c.operator, c.value);
    });
    const met = config.requireAll === false
      ? results.some((r: boolean) => r)
      : results.every((r: boolean) => r);
    if (!met) conditionsMet = false;
    condDetails.push(
      ...config.conditions.map((c: { field: string; operator: string; value: unknown }, i: number) =>
        `${c.field} ${c.operator} ${c.value}: ${results[i] ? "✓" : "✗"}`
      )
    );
  }

  // OR conditions (at least one must match)
  if (config.orConditions && Array.isArray(config.orConditions)) {
    const results = config.orConditions.map((c: { field: string; operator: string; value: unknown }) => {
      const val = listing[c.field as keyof ListingData];
      return evaluateCondition(val, c.operator, c.value);
    });
    if (!results.some((r: boolean) => r)) conditionsMet = false;
    condDetails.push(
      "OR(" + config.orConditions.map((c: { field: string; operator: string; value: unknown }, i: number) =>
        `${c.field} ${c.operator} ${c.value}: ${results[i] ? "✓" : "✗"}`
      ).join(", ") + ")"
    );
  }

  // Single field/operator
  if (!config.conditions && !config.orConditions && config.field && config.operator) {
    const val = listing[config.field as keyof ListingData];
    conditionsMet = evaluateCondition(val, config.operator, config.value);
    condDetails.push(`${config.field}=${val} ${config.operator} ${config.value}`);
  }

  // If no conditions at all, just filters: match if passed all filters
  // BUT: skip if only filters are present without actual conditions
  // This prevents "duplicates_*" rules from matching on country alone
  // (actual duplicate detection requires cross-referencing other listings)
  if (!config.conditions && !config.orConditions && !config.field) {
    // Rules with only filters but no conditions are structural rules
    // (like duplicate checks) that need additional logic not yet implemented
    return { matched: false, details: "Filters-only rule (no conditions to evaluate)" };
  }

  return { matched: conditionsMet, details: condDetails.join(", ") };
}

function evaluateCondition(value: unknown, operator: string, target: unknown): boolean {
  if (value === undefined || value === null) {
    if (operator === "empty" || operator === "is_null") return true;
    if (operator === "not_empty" || operator === "is_not_null") return false;
    // Unknown field = skip the rule (don't match on missing data)
    return false;
  }

  switch (operator) {
    case "lt":
    case "<":
      return Number(value) < Number(target);
    case "lte":
    case "<=":
      return Number(value) <= Number(target);
    case "gt":
    case ">":
      return Number(value) > Number(target);
    case "gte":
    case ">=":
      return Number(value) >= Number(target);
    case "eq":
    case "==":
      return String(value).toLowerCase() === String(target).toLowerCase();
    case "neq":
    case "!=":
      return String(value).toLowerCase() !== String(target).toLowerCase();
    case "in":
      return Array.isArray(target) && target.map((t: unknown) => String(t).toLowerCase()).includes(String(value).toLowerCase());
    case "not_in":
      return Array.isArray(target) && !target.map((t: unknown) => String(t).toLowerCase()).includes(String(value).toLowerCase());
    case "contains":
      return String(value).toLowerCase().includes(String(target).toLowerCase());
    case "not_contains":
      return !String(value).toLowerCase().includes(String(target).toLowerCase());
    case "matches":
      try {
        return new RegExp(String(target), "i").test(String(value));
      } catch {
        return false; // invalid regex in rule config
      }
    case "empty":
      return !value || (typeof value === "string" && value.trim() === "");
    case "not_empty":
      return !!value && (typeof value !== "string" || value.trim() !== "");
    case "is_true":
      return value === true;
    case "is_false":
      return value === false || !value;
    default:
      return false;
  }
}

function evaluateRegexRule(listing: ListingData, config: RuleConfig): { matched: boolean; details: string; matchedPatterns: string[] } {
  // Pre-flight filters (same as simple rules)
  if (config.categoryFilter && Array.isArray(config.categoryFilter)) {
    const rawCat = (listing.category || "").toLowerCase();
    const cat = rawCat.replace("listing::", "").replace("realestate", "real_estate").replace(/^car$/i, "cars");
    // Empty category must not pass: ""'s substring check matches any filter.
    if (!cat || !config.categoryFilter.some((f: string) => { const nf = f.toLowerCase(); return cat.includes(nf) || nf.includes(cat); })) {
      return { matched: false, details: `category ${listing.category} not in ${config.categoryFilter}`, matchedPatterns: [] };
    }
  }
  if (config.countryFilter && Array.isArray(config.countryFilter)) {
    if (!countryMatches(listing.country, config.countryFilter)) {
      return { matched: false, details: `country ${listing.country} not in ${config.countryFilter}`, matchedPatterns: [] };
    }
  }
  if (config.excludeTypes && Array.isArray(config.excludeTypes)) {
    const reType = (listing.realEstateType || "").toLowerCase();
    if (reType && config.excludeTypes.some((f: string) => { const nf = f.toLowerCase().replace(/ /g, "_"); return reType === nf || reType === f.toLowerCase() || reType.replace(/_/g, " ") === f.toLowerCase(); })) {
      return { matched: false, details: `type ${listing.realEstateType} excluded`, matchedPatterns: [] };
    }
  }
  if (config.typeFilter && Array.isArray(config.typeFilter)) {
    const reType = (listing.realEstateType || "").toLowerCase();
    if (!reType || !config.typeFilter.some((f: string) => reType === f.toLowerCase())) {
      return { matched: false, details: `type ${listing.realEstateType} not in ${config.typeFilter}`, matchedPatterns: [] };
    }
  }
  if (config.accountTypeFilter && Array.isArray(config.accountTypeFilter)) {
    const acct = (listing.officeSubscription || listing.accountType || "").toLowerCase();
    if (!acct || !config.accountTypeFilter.some((f: string) => acct.includes(f.toLowerCase()))) {
      return { matched: false, details: `accountType not in ${config.accountTypeFilter}`, matchedPatterns: [] };
    }
  }
  if (config.maxPrice !== undefined && config.maxPrice !== null) {
    const price = listing.priceUsd || listing.price || 0;
    if (price > Number(config.maxPrice)) {
      return { matched: false, details: `price > maxPrice`, matchedPatterns: [] };
    }
  }

  const patterns = config.patterns || [];
  const fields = config.fields || ["title", "description"];
  const matchedPatterns: string[] = [];

  for (const pattern of patterns) {
    try {
      const regex = new RegExp(pattern, "i");
      for (const field of fields) {
        const value = listing[field as keyof ListingData];
        if (typeof value === "string" && regex.test(value)) {
          matchedPatterns.push(`"${pattern}" in ${field}`);
        }
      }
    } catch {
      // Skip invalid regex
    }
  }

  // Also check text lists
  if (config.textLists) {
    for (const [listName, words] of Object.entries(config.textLists)) {
      for (const field of fields) {
        const value = listing[field as keyof ListingData];
        if (typeof value === "string") {
          const lowerValue = value.toLowerCase();
          for (const word of words) {
            if (lowerValue.includes(word.toLowerCase())) {
              matchedPatterns.push(`"${word}" (${listName}) in ${field}`);
            }
          }
        }
      }
    }
  }

  if (matchedPatterns.length === 0) {
    return { matched: false, details: "No pattern matches", matchedPatterns: [] };
  }

  // Check exclude patterns (if ANY exclude matches, rule does NOT fire)
  if (config.excludePatterns && Array.isArray(config.excludePatterns)) {
    const excludeFields: string[] = Array.isArray(config.excludeFields) ? config.excludeFields as string[] : ["title", "description"];
    for (const pattern of config.excludePatterns as string[]) {
      try {
        const regex = new RegExp(pattern, "i");
        for (const field of excludeFields) {
          const value = listing[field as keyof ListingData];
          if (typeof value === "string" && regex.test(value)) {
            return { matched: false, details: `Excluded by "${pattern}" in ${field}`, matchedPatterns: [] };
          }
        }
      } catch { /* skip invalid */ }
    }
  }

  return {
    matched: true,
    details: `Matched: ${matchedPatterns.join("; ")}`,
    matchedPatterns,
  };
}

// ─── Hybrid Vision Rule Evaluator ───────────────────────────────
// Properly checks GPT/Claude vision scores against thresholds
function evaluateHybridVisionRule(listing: ListingData, config: RuleConfig): { matched: boolean; details: string } {
  // ─── Pre-flight filters (same as simple rules, with country normalization) ───
  if (config.countryFilter && Array.isArray(config.countryFilter)) {
    if (!countryMatches(listing.country, config.countryFilter)) {
      return { matched: false, details: `country ${listing.country} not in ${config.countryFilter}` };
    }
  }
  if (config.excludeCountries && Array.isArray(config.excludeCountries)) {
    if (listing.country && countryMatches(listing.country, config.excludeCountries)) {
      return { matched: false, details: `country ${listing.country} excluded` };
    }
  }
  if (config.categoryFilter && Array.isArray(config.categoryFilter)) {
    const rawCat = (listing.category || "").toLowerCase();
    const cat = rawCat.replace("listing::", "").replace("realestate", "real_estate").replace(/^car$/i, "cars");
    // Empty category must not pass: ""'s substring check matches any filter.
    if (!cat || !config.categoryFilter.some((f: string) => { const nf = f.toLowerCase(); return cat.includes(nf) || nf.includes(cat); })) {
      return { matched: false, details: `category ${listing.category} not in ${config.categoryFilter}` };
    }
  }
  if (config.maxPrice !== undefined && config.maxPrice !== null) {
    const price = listing.priceUsd || listing.price || 0;
    if (price > Number(config.maxPrice)) {
      return { matched: false, details: `price ${price} > maxPrice ${config.maxPrice}` };
    }
  }
  if (config.minPrice !== undefined && config.minPrice !== null) {
    const price = listing.priceUsd || listing.price || 0;
    if (price < Number(config.minPrice)) {
      return { matched: false, details: `price ${price} < minPrice ${config.minPrice}` };
    }
  }
  if (config.excludeTypes && Array.isArray(config.excludeTypes)) {
    const reType = (listing.realEstateType || "").toLowerCase();
    if (reType && config.excludeTypes.some((f: string) => { const nf = f.toLowerCase().replace(/ /g, "_"); return reType === nf || reType === f.toLowerCase() || reType.replace(/_/g, " ") === f.toLowerCase(); })) {
      return { matched: false, details: `type ${listing.realEstateType} excluded` };
    }
  }
  if (config.typeFilter && Array.isArray(config.typeFilter)) {
    const reType = (listing.realEstateType || "").toLowerCase();
    if (!reType || !config.typeFilter.some((f: string) => reType === f.toLowerCase())) {
      return { matched: false, details: `type ${listing.realEstateType} not in ${config.typeFilter}` };
    }
  }
  if (config.accountTypeFilter && Array.isArray(config.accountTypeFilter)) {
    const acct = (listing.officeSubscription || listing.accountType || "").toLowerCase();
    if (!acct || !config.accountTypeFilter.some((f: string) => acct.includes(f.toLowerCase()))) {
      return { matched: false, details: `accountType not in ${config.accountTypeFilter}` };
    }
  }
  if (config.excludeOffices && Array.isArray(config.excludeOffices)) {
    const officeId = listing.office ? Number(listing.office) : (listing.officeId ? Number(listing.officeId) : null);
    if (officeId && config.excludeOffices.includes(officeId)) {
      return { matched: false, details: `office ${officeId} excluded` };
    }
  }
  if (config.excludeTitleKeywords && Array.isArray(config.excludeTitleKeywords)) {
    const title = (listing.title || "").toLowerCase();
    if (config.excludeTitleKeywords.some((kw: string) => title.includes(kw.toLowerCase()))) {
      return { matched: false, details: "title contains excluded keyword" };
    }
  }

  // ─── Vision score checks ───
  const condition = listing.chatGptPropertyCondition;
  const conclusion = listing.chatGptConclusion;
  const conclusionNum = conclusion !== undefined && conclusion !== null ? Number(conclusion) : null;
  const watermarkText = (listing.chatGptWatermarkText || "").toLowerCase();
  const watermarkShare = listing.chatGptWatermarkShare;

  // Type 1: Score thresholds (condition AND conclusion must be below thresholds)
  if (config.scoreThresholds) {
    const thresholds = config.scoreThresholds as { condition?: number; conclusion?: number };
    
    // If no vision scores available, rule cannot match (don't flag without data)
    if (condition === undefined || condition === null || conclusionNum === null) {
      return { matched: false, details: `no vision scores available (condition=${condition}, conclusion=${conclusion})` };
    }

    const conditionMatch = thresholds.condition !== undefined ? condition <= thresholds.condition : true;
    const conclusionMatch = thresholds.conclusion !== undefined ? conclusionNum <= thresholds.conclusion : true;

    if (conditionMatch && conclusionMatch) {
      return {
        matched: true,
        details: `condition=${condition}≤${thresholds.condition}, conclusion=${conclusionNum}≤${thresholds.conclusion}`,
      };
    }
    return {
      matched: false,
      details: `scores OK: condition=${condition}>${thresholds.condition || "n/a"}, conclusion=${conclusionNum}>${thresholds.conclusion || "n/a"}`,
    };
  }

  // Type 2: Watermark keyword check
  if (config.checkType === "watermark" && config.watermarkKeywords) {
    if (!watermarkText) {
      return { matched: false, details: "no watermark text detected" };
    }
    const keywords = config.watermarkKeywords as string[];
    const matchedKw = keywords.filter((kw: string) => watermarkText.includes(kw.toLowerCase()));
    if (matchedKw.length > 0) {
      return { matched: true, details: `watermark text "${watermarkText}" contains: ${matchedKw.join(", ")}` };
    }
    return { matched: false, details: `watermark text "${watermarkText}" doesn't match keywords` };
  }

  // Type 3: Unidentifiable property check
  if (config.checkType === "unidentifiable") {
    // Check if condition is 0 (mapped from "Unidentifiable" text) or null with images
    const isUnidentifiable = condition === 0 || 
      (typeof listing.chatGptConclusion === "string" && listing.chatGptConclusion.toLowerCase().includes("unidentif"));
    
    if (isUnidentifiable) {
      return { matched: true, details: `property unidentifiable (condition=${condition})` };
    }
    // Also flag very low condition with low conclusion as potentially unidentifiable
    if (condition !== null && condition !== undefined && condition <= 1.0 && conclusionNum !== null && conclusionNum <= 1.5) {
      return { matched: true, details: `near-unidentifiable: condition=${condition}, conclusion=${conclusionNum}` };
    }
    return { matched: false, details: `property identifiable (condition=${condition})` };
  }

  // Type 4: Watermark size check
  if (config.checkType === "watermark_size") {
    if (watermarkShare === undefined || watermarkShare === null || watermarkShare === 0) {
      return { matched: false, details: "no watermarks detected" };
    }
    const threshold = (config.watermarkShareThreshold as number) || 3;
    if (watermarkShare >= threshold) {
      return { matched: true, details: `watermark share ${watermarkShare} >= ${threshold}` };
    }
    return { matched: false, details: `watermark share ${watermarkShare} < ${threshold}` };
  }

  // Fallback: no recognized vision check type
  return { matched: false, details: "no vision check type matched in config" };
}

// ─── Accuracy Rule Evaluator (LAS integration) ──────────────────
// Checks listing.accuracyFlags against LAS flag requirements in rule config
function evaluateAccuracyRule(listing: ListingData, config: RuleConfig): { matched: boolean; details: string } {
  const flags: string[] = (listing as any).accuracyFlags || [];
  const score: number | undefined = (listing as any).accuracyScore;
  const acctType = (listing.officeSubscription || (listing as any).accountType || "").toLowerCase();

  // Account type filter
  if (config.accountTypeFilter && Array.isArray(config.accountTypeFilter)) {
    if (!acctType || !config.accountTypeFilter.some((f: string) => acctType.includes(f.toLowerCase()))) {
      return { matched: false, details: `accountType ${acctType || "unknown"} not in ${config.accountTypeFilter}` };
    }
  }

  // No accuracy data at all → skip
  if (flags.length === 0 && score === undefined) {
    return { matched: false, details: "no LAS accuracy data" };
  }

  // Score-based check (e.g. las_score_critical)
  if (config.maxAccuracyScore !== undefined && config.maxAccuracyScore !== null) {
    if (score !== undefined && score <= Number(config.maxAccuracyScore)) {
      return { matched: true, details: `accuracy score ${score.toFixed(2)} ≤ ${config.maxAccuracyScore}` };
    }
    if (score === undefined) {
      return { matched: false, details: "no accuracy score available" };
    }
    return { matched: false, details: `accuracy score ${score.toFixed(2)} > ${config.maxAccuracyScore}` };
  }

  // Single flag check
  if (config.accuracyFlag && typeof config.accuracyFlag === "string") {
    if (flags.includes(config.accuracyFlag)) {
      return { matched: true, details: `LAS flag: ${config.accuracyFlag} (score: ${score?.toFixed(2) ?? "n/a"})` };
    }
    return { matched: false, details: `flag ${config.accuracyFlag} not in [${flags.join(", ")}]` };
  }

  // Multi-flag check (matchAny = true → any flag matches; false → all must match)
  if (config.accuracyFlags && Array.isArray(config.accuracyFlags)) {
    const matchAny = config.matchAny !== false; // default true
    const matched = matchAny
      ? config.accuracyFlags.some((f: string) => flags.includes(f))
      : config.accuracyFlags.every((f: string) => flags.includes(f));

    if (matched) {
      const found = config.accuracyFlags.filter((f: string) => flags.includes(f));
      return { matched: true, details: `LAS flags: ${found.join(", ")} (score: ${score?.toFixed(2) ?? "n/a"})` };
    }
    return { matched: false, details: `flags ${config.accuracyFlags.join(", ")} not found in [${flags.join(", ")}]` };
  }

  return { matched: false, details: "no accuracy check matched in config" };
}

function evaluateOfficeRule(listing: ListingData, config: RuleConfig): { matched: boolean; details: string } {
  const officeNames = (config.officeNames || []).map((n: string) => n.toLowerCase());
  // Normalize to strings — configs may store numeric ids while the listing
  // field is a string (or vice versa), and a mixed-type includes() never matches.
  const officeIds = (config.officeIds || []).map((id) => String(id));

  const listingOffice = (listing.officeGroupName || listing.office || "").toLowerCase();

  if (officeNames.length > 0 && officeNames.some((n: string) => listingOffice.includes(n))) {
    return { matched: true, details: `Office "${listingOffice}" matches rule` };
  }
  if (officeIds.length > 0 && officeIds.includes(String(listing.office ?? ""))) {
    return { matched: true, details: `Office ID "${listing.office}" matches rule` };
  }

  return { matched: false, details: `Office "${listingOffice}" not in rule` };
}

// ─── Moderation List Resolution ──────────────────────────────────
// Rules can reference moderationLists rows via config.listRef /
// additionalListRef (match lists) and excludeListRef (exclusion list).
// Resolve those references into the patterns/textLists/excludePatterns
// shape the regex evaluator understands; without this step listRef rules
// have no conditions at all and silently never match.

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

type ModListItem = { value: string; type?: string; pattern?: string; flags?: string };

function resolveListRefs(
  config: RuleConfig,
  listsByName: Record<string, { items?: ModListItem[] } | undefined>,
): RuleConfig {
  const refNames = [config.listRef, config.additionalListRef].filter(
    (n): n is string => typeof n === "string",
  );
  const excludeName = typeof config.excludeListRef === "string" ? config.excludeListRef : undefined;
  if (refNames.length === 0 && !excludeName) return config;

  const resolved: RuleConfig = { ...config };
  const patterns: string[] = [...(config.patterns || [])];
  const textLists: Record<string, string[]> = { ...(config.textLists || {}) };

  for (const name of refNames) {
    const list = listsByName[name];
    if (!list) continue;
    const words: string[] = [];
    for (const item of list.items || []) {
      if (item.type === "regex" && item.pattern) {
        patterns.push(item.pattern);
      } else if (item.value) {
        words.push(item.value);
      }
    }
    if (words.length > 0) textLists[name] = [...(textLists[name] || []), ...words];
  }
  if (patterns.length > 0) resolved.patterns = patterns;
  if (Object.keys(textLists).length > 0) resolved.textLists = textLists;

  if (excludeName) {
    const list = listsByName[excludeName];
    if (list) {
      const excludePatterns: string[] = [...((config.excludePatterns as string[]) || [])];
      for (const item of list.items || []) {
        if (item.type === "regex" && item.pattern) excludePatterns.push(item.pattern);
        else if (item.value) excludePatterns.push(escapeRegex(item.value));
      }
      if (excludePatterns.length > 0) resolved.excludePatterns = excludePatterns;
    }
  }

  return resolved;
}


export {
  evaluateSimpleRule,
  evaluateCondition,
  evaluateRegexRule,
  evaluateHybridVisionRule,
  evaluateAccuracyRule,
  evaluateOfficeRule,
  resolveListRefs,
  countryMatches,
  toCountryCode,
};
