// Golden-fixture generator for the Ruby port of the moderation rule engine.
//
// This script extracts the PURE evaluator functions from convex/moderation.ts
// (no rewrites — the real TS code is executed), runs every fixture from
// fixtures.json through the same deterministic decision flow as the
// moderateListing action, and writes the expected results to
// rails/spec/fixtures/golden/expected.json.
//
// Run with:  bun scripts/golden/generate.ts
//
// Stubs (documented):
// - The LLM phase is not executed: evaluation stops at outcome "needs_llm"
//   and records which auto_ai/former_manual rules fired. The LLM routing
//   itself is unit-tested on the Ruby side (engine_spec.rb).
// - Step 3b (on-demand vision) is skipped. No fixture carries imageUrls, so
//   the real action would skip the block too (it requires imageUrls.length
//   > 0); the generator throws if a fixture would ever reach it.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const repoRoot = join(import.meta.dir, "..", "..");

// ── 1. Extract the pure prelude of convex/moderation.ts ────────────────────
// Everything above the "Internal functions" marker is pure (types, country
// maps, evaluators, resolveListRefs); below it live Convex queries/actions.
const source = readFileSync(join(repoRoot, "convex", "moderation.ts"), "utf8");
const MARKER = "// ─── Internal functions";
const markerIdx = source.indexOf(MARKER);
if (markerIdx < 0) throw new Error(`marker not found in convex/moderation.ts: ${MARKER}`);

const prelude = source
  .slice(0, markerIdx)
  .split("\n")
  .filter((line) => !/^import\s/.test(line))
  .map((line) => line.replace(/^export\s+(function|const)\b/, "$1"))
  .join("\n");

const generated =
  "// AUTO-GENERATED by scripts/golden/generate.ts — pure prelude of convex/moderation.ts. Do not edit.\n" +
  prelude +
  "\nexport {\n" +
  "  evaluateSimpleRule,\n" +
  "  evaluateCondition,\n" +
  "  evaluateRegexRule,\n" +
  "  evaluateHybridVisionRule,\n" +
  "  evaluateAccuracyRule,\n" +
  "  evaluateOfficeRule,\n" +
  "  resolveListRefs,\n" +
  "  countryMatches,\n" +
  "  toCountryCode,\n" +
  "};\n";

const genPath = join(import.meta.dir, ".generated", "moderation_pure.ts");
mkdirSync(dirname(genPath), { recursive: true });
writeFileSync(genPath, generated);

const mod: any = await import(genPath);

// ── 2. Load seed data + fixtures ────────────────────────────────────────────
const seedRules = JSON.parse(readFileSync(join(repoRoot, "rails", "db", "seed_data", "rules.json"), "utf8"));
const seedLists = JSON.parse(readFileSync(join(repoRoot, "rails", "db", "seed_data", "lists.json"), "utf8"));
const fixturesDoc = JSON.parse(readFileSync(join(import.meta.dir, "fixtures.json"), "utf8"));

const allRules: any[] = [...seedRules, ...fixturesDoc.extraRules];
const allLists: any[] = [...seedLists, ...fixturesDoc.extraLists];

// ── 3. Prepare rules exactly like the moderateListing action ───────────────
// getEnabledRules only returns enabled rules (the seeding path defaults the
// flag to true); list refs are resolved; rules are sorted by priority with
// JS's stable Array#sort.
const listsByName: Record<string, any> = {};
for (const list of allLists) {
  if (!(list.name in listsByName)) listsByName[list.name] = list;
}
const rules = allRules
  .filter((r) => (r.enabled ?? true) === true)
  .map((r) => ({ ...r, config: mod.resolveListRefs(r.config ?? {}, listsByName) }));
rules.sort((a, b) => a.priority - b.priority);

// ── 4. Deterministic decision flow (verbatim from the action body) ─────────
interface RuleMatch {
  ruleName: string;
  ruleCategory: string;
  tier: string;
  action: string;
  message?: string;
  details?: string;
}

interface Outcome {
  matches: string[];
  outcome: string;
  needsLlm: boolean;
  llmRuleMatches: string[];
  sellerMessage: string | null;
}

function moderate(listing: any): Outcome {
  const ruleMatches: RuleMatch[] = [];
  let needsLlm = false;
  const llmRuleMatches: string[] = [];

  const hasVisionData = listing.chatGptPropertyCondition != null;

  // 2. Deterministic rules: simple_code + hybrid_vision + internal
  //    (accuracy is commented out of this filter in moderation.ts — disabled)
  const deterministicRules = rules.filter(
    (r) => r.category === "simple_code" || r.category === "hybrid_vision" || r.category === "internal"
  );
  for (const rule of deterministicRules) {
    let result: { matched: boolean; details: string };
    if (rule.category === "accuracy") {
      result = mod.evaluateAccuracyRule(listing, rule.config);
    } else if (rule.category === "hybrid_vision") {
      if (!hasVisionData) continue;
      result = mod.evaluateHybridVisionRule(listing, rule.config);
    } else if (rule.config.officeIds || rule.config.officeNames) {
      result = mod.evaluateOfficeRule(listing, rule.config);
    } else if (rule.config.patterns || rule.config.textLists) {
      result = mod.evaluateRegexRule(listing, rule.config);
    } else {
      result = mod.evaluateSimpleRule(listing, rule.config);
    }
    if (result.matched) {
      ruleMatches.push({
        ruleName: rule.name,
        ruleCategory: rule.category,
        tier: rule.tier,
        action: rule.action,
        message: rule.sellerMessage,
        details: result.details,
      });
    }
  }

  const names = () => ruleMatches.map((m) => m.ruleName);

  // Immediate rejection (tier: auto)
  const autoRejects = ruleMatches.filter((m) => m.tier === "auto" && m.action === "reject");
  if (autoRejects.length > 0) {
    const sellerMsg = autoRejects[0].message || "Your listing does not meet our quality standards.";
    return { matches: names(), outcome: "rejected", needsLlm: false, llmRuleMatches: [], sellerMessage: sellerMsg };
  }

  // Auto-approve short-circuit
  const autoApproves = ruleMatches.filter((m) => m.tier === "auto" && m.action === "approve");
  if (autoApproves.length > 0) {
    const sellerMsg = autoApproves.map((a) => a.message).filter(Boolean).join("\n");
    return { matches: names(), outcome: "approved", needsLlm: false, llmRuleMatches: [], sellerMessage: sellerMsg || null };
  }

  const autoNotices = ruleMatches.filter((m) => m.tier === "auto" && m.action === "notice");

  // 3. AI-trigger rules: auto_ai + former_manual
  const aiTriggerRules = rules.filter((r) => r.category === "auto_ai" || r.category === "former_manual");
  for (const rule of aiTriggerRules) {
    const result =
      rule.config.patterns || rule.config.textLists
        ? mod.evaluateRegexRule(listing, rule.config)
        : mod.evaluateSimpleRule(listing, rule.config);
    if (result.matched) {
      ruleMatches.push({
        ruleName: rule.name,
        ruleCategory: rule.category,
        tier: rule.tier,
        action: rule.action,
        message: rule.sellerMessage,
        details: result.details,
      });
      llmRuleMatches.push(rule.name);
      needsLlm = true;
    }
  }

  // 3b. On-demand vision is stubbed; guarantee no fixture would trigger it.
  if (needsLlm && !hasVisionData && listing.imageUrls && listing.imageUrls.length > 0) {
    throw new Error("fixture would trigger on-demand vision (step 3b); fixtures must not carry imageUrls");
  }

  // 4. AI-trigger match -> stop here; the LLM phase is exercised separately.
  if (needsLlm) {
    return { matches: names(), outcome: "needs_llm", needsLlm: true, llmRuleMatches, sellerMessage: null };
  }

  // 6. Matched rules that still need human review
  const manualMatches = ruleMatches.filter(
    (m) => m.tier === "manual" || m.tier === "verify" || m.action === "flag"
  );
  if (manualMatches.length > 0) {
    return { matches: names(), outcome: "manual", needsLlm: false, llmRuleMatches: [], sellerMessage: null };
  }

  // 7. If only notices, approve with notice
  if (autoNotices.length > 0) {
    const sellerMsg = autoNotices.map((n) => n.message).filter(Boolean).join("\n");
    return { matches: names(), outcome: "notice", needsLlm: false, llmRuleMatches: [], sellerMessage: sellerMsg || null };
  }

  // 8. All clear -> approve
  return { matches: names(), outcome: "approved", needsLlm: false, llmRuleMatches: [], sellerMessage: null };
}

// ── 5. Run fixtures + sanity checks ─────────────────────────────────────────
const expected: Array<{ label: string } & Outcome> = [];
const problems: string[] = [];
const distinctMatched = new Set<string>();

for (const fixture of fixturesDoc.fixtures) {
  const result = moderate(fixture.listing);
  for (const name of result.matches) distinctMatched.add(name);

  const exp = fixture.expect ?? {};
  if (exp.outcome && exp.outcome !== result.outcome) {
    problems.push(`${fixture.label}: expected outcome ${exp.outcome}, got ${result.outcome} (matches: ${result.matches.join(", ") || "none"})`);
  }
  for (const name of exp.mustMatch ?? []) {
    if (!result.matches.includes(name)) {
      problems.push(`${fixture.label}: expected rule ${name} to match (got: ${result.matches.join(", ") || "none"})`);
    }
  }
  for (const name of exp.mustNotMatch ?? []) {
    if (result.matches.includes(name)) {
      problems.push(`${fixture.label}: rule ${name} must NOT match`);
    }
  }

  expected.push({ label: fixture.label, ...result });
}

const labels = new Set(expected.map((e) => e.label));
if (labels.size !== expected.length) problems.push("duplicate fixture labels");
if (distinctMatched.size < 10) {
  problems.push(`only ${distinctMatched.size} distinct rules fired across the suite (need >= 10)`);
}

if (problems.length > 0) {
  console.error("Fixture sanity check FAILED:\n - " + problems.join("\n - "));
  process.exit(1);
}

// ── 6. Write expected.json ──────────────────────────────────────────────────
const outPath = join(repoRoot, "rails", "spec", "fixtures", "golden", "expected.json");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, JSON.stringify(expected, null, 2) + "\n");

const outcomeCounts: Record<string, number> = {};
for (const e of expected) outcomeCounts[e.outcome] = (outcomeCounts[e.outcome] ?? 0) + 1;
console.log(`Wrote ${expected.length} golden expectations to ${outPath}`);
console.log(`Outcomes: ${JSON.stringify(outcomeCounts)}`);
console.log(`Distinct rules fired: ${distinctMatched.size}`);
console.log([...distinctMatched].sort().join(", "));
